version: '3'
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    volumes:
      - postgresql_db:/var/lib/postgresql
    ports:
      - "5432:5432"
volumes:
  postgresql_db: